# Generated by Django 5.2.8 on 2025-11-23 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código único del proyecto, ej. PRJ-001.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del proyecto de obra.",
                        max_length=200,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Ubicación principal de la obra (ciudad, dirección, etc.).",
                        max_length=200,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Fecha real de inicio del proyecto."),
                ),
                (
                    "end_date_estimated",
                    models.DateField(
                        help_text="Fecha estimada de finalización del proyecto."
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Progreso físico global del proyecto en porcentaje.",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("completed", "Completado"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="active",
                        help_text="Estado actual del proyecto.",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadatos flexibles del proyecto (supervisor, presupuesto, etc.).",
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 del contenido actual del proyecto.",
                        max_length=64,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        help_text="Hash SHA-256 del estado anterior del proyecto.",
                        max_length=64,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Última fecha de actualización del registro.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
    ]
