# Generated by Django 5.2.8 on 2025-11-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que registró el proyecto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que modificó el proyecto.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
