# Generated by Django 5.2.8 on 2025-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_document_updated_by_document_uploaded_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="original_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
