# Generated by Django 5.2.8 on 2025-11-23 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("history", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="changerecord",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que realizó la modificación",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="field_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historyrecord",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_records",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="historyrecord",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable, puede ser null si es acción del sistema",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="history_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
