# Generated by Django 5.2.8 on 2025-11-24 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress_reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="progressreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que registró el avance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progress_reports_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="progressreport",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que actualizó el avance.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="progress_reports_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
