# Generated by Django 5.2.8 on 2025-11-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Documento creado"),
                            ("version_created", "Nueva versión creada"),
                            ("duplicate_detected", "Duplicado detectado"),
                            ("metadata_updated", "Metadata actualizada"),
                            ("file_changed", "Archivo modificado"),
                            ("status_changed", "Estado modificado"),
                            ("integrity_checked", "Integridad verificada"),
                        ],
                        default="created",
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("metadata_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Document histories",
                "ordering": ["document_id", "-version_number", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/")),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("file_hash", models.CharField(blank=True, max_length=64)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("previous_hash", models.CharField(blank=True, max_length=64)),
                ("is_duplicate", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "author",
                    models.CharField(
                        blank=True, help_text="Autor del documento.", max_length=200
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de documento (plano, informe, contrato, etc.).",
                        max_length=100,
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de emisión del documento.",
                        null=True,
                    ),
                ),
                (
                    "responsible_area",
                    models.CharField(
                        blank=True,
                        help_text="Área responsable (Ingeniería, Supervisión, Calidad, etc.).",
                        max_length=150,
                    ),
                ),
                (
                    "sensitivity_level",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("restricted", "Restringida"),
                        ],
                        default="low",
                        help_text="Nivel de sensibilidad del documento.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("observed", "Observed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="deliveries.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id", "title", "-version_number"],
            },
        ),
    ]
