# Generated by Django 5.2.8 on 2025-11-23 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "model_name",
                    models.CharField(
                        help_text="Nombre del modelo afectado: purchase, delivery, project, etc.",
                        max_length=80,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID del objeto afectado (string para flexibilidad)",
                        max_length=80,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="Campo que fue modificado", max_length=120
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True, help_text="Valor anterior del campo", null=True
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True, help_text="Valor nuevo del campo", null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Razón del cambio (si el usuario aporta este dato)",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        help_text="Fecha y hora del cambio",
                    ),
                ),
                (
                    "hash_change",
                    models.CharField(
                        help_text="Hash sha256(old_value + new_value + timestamp)",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Record",
                "verbose_name_plural": "Change Records",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HistoryRecord",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_type",
                    models.CharField(
                        help_text="Tipo de acción registrada (purchase_created, delivery_updated, etc.)",
                        max_length=80,
                    ),
                ),
                (
                    "related_type",
                    models.CharField(
                        help_text="Entidad afectada: purchase, delivery, progress, document, validation, alert, system",
                        max_length=40,
                    ),
                ),
                (
                    "related_id",
                    models.CharField(
                        help_text="ID del registro afectado en texto, para permitir flexibility",
                        max_length=80,
                    ),
                ),
                (
                    "previous_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hash previo del registro",
                        max_length=128,
                    ),
                ),
                (
                    "new_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nuevo hash del registro",
                        max_length=128,
                    ),
                ),
                (
                    "previous_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos resumidos antes del cambio",
                        null=True,
                    ),
                ),
                (
                    "new_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos resumidos después del cambio",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Metadatos adicionales del evento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "History Record",
                "verbose_name_plural": "History Records",
                "ordering": ["-created_at"],
            },
        ),
    ]
