# Generated by Django 5.2.8 on 2025-11-23 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("delivery", "Delivery"),
                            ("progress", "Progress Report"),
                            ("document", "Document"),
                            ("system", "System Event"),
                            ("validation", "Validation"),
                            ("supplier_risk", "Supplier Risk"),
                            ("inactivity", "Inactivity"),
                            ("overprice_trend", "Overprice Trend"),
                            ("incomplete_delivery", "Incomplete Delivery"),
                            ("negative_stock", "Negative Stock"),
                            ("physical_stagnation", "Physical Stagnation"),
                        ],
                        max_length=50,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(5)],
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("warning", "Warning"),
                            ("info", "Info"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
