# Generated by Django 5.2.8 on 2025-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0001_initial"),
        ("projects", "0002_project_created_by_project_updated_by"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                fields=("project", "item_type", "item_id"), name="unique_alert_per_item"
            ),
        ),
    ]
