# Generated by Django 5.2.8 on 2025-11-24 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
