# Generated by Django 5.2.8 on 2025-11-24 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliveries", "0002_alter_delivery_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que registró la entrega.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Último usuario que modificó la entrega.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
